[env:stm32u585]
platform = ststm32
framework = arduino
board = genericSTM32U585CIU6_custom

monitor_speed = 115200
monitor_dtr = 1

build_src_filter =
  -<*>
  +<main2.cpp>

lib_deps =

build_flags =
  -O3
  -ffast-math
  -funroll-loops

  -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
  -D USBCON
  -D STM32U585xx

upload_protocol = dfu